### ISSUE TITLE
`GatewayProvider.callContract` fails when using `blockTag` or `blockNumber`.

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet-jvm#154]
Constructed request is probably incorrect - blockHash is always used.

**Comment by florian-bellotti** [comment]
https://github.com/software-mansion/starknet-jvm/blob/main/lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt#L61

When the blockId is a number or a tag, it should set the `blockNumber` query parameter.
And, it should set `blockHash` when blockId is a hash.
