### ISSUE TITLE
Network errors when trying to estimate fees

### ISSUE THREAD

**Issue by kamilargent** [software-mansion/starknet-jvm#156]
## Summary
When trying to estimate fees I have come across a few issues with incorrect request

### Incorrect parameter `blockTag`
Invoke`StandardAccount#estimateFee` 
Error returned:
 `{"code": "StarkErrorCode.MALFORMED_REQUEST", "message": "Query fields should be a subset of {'blockHash', 'blockNumber'}; got: {'blockTag'}."}`
RCA: `blockNumber` should be used instead of `blockTag`

### Missing `type`
Invoke:`GatewayProvider#getEstimateFee(request: InvokeTransaction, blockNumber: Int)`
Error returned:
```{"code": "StarkErrorCode.MALFORMED_REQUEST", "message": "Transaction of version 1 is expected to contain the `type` field."}```
RCA: missing `type` in the request body

**Comment by Solpatium** [comment]
The first issue should be fixed by https://github.com/software-mansion/starknet-jvm/pull/159.

**Comment by cptartur** [comment]
Second issue should be fixed by #161 If the error still persists, feel free to reopen this issue.
