### ISSUE TITLE
Consider exposing more details as public

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/starknet-jvm#164]
> I did a quick check through the SDK and I think those functions / classes could be public instead of internal:
> - HttpRequest` & HttpResponseDeserializer
> - Request, Felt`, Json extensions
> - Transaction#toPayload
> - GatewayProvider` - all constructor params could be public, it's useful if u want to make the request on your own

**Comment by Solpatium** [comment]
We've discussed this and decided to make public:
- HttpRequest and HttpResponseDeserializer. There is a problem with `HttpResponseDeserializer` - it is translated as kotlin's function to java. It has to be changed to either be `Function` from java or use https://kotlinlang.org/docs/fun-interfaces.html#sam-conversions.
- `BigInteger.toFelt`, but it has to be moved to extensions.BigInteger.
- `Transaction.toPayload`
- `GatewayProvider` - all constructor params can be public

We've discussed Requests and decided it would be the best if applications wrapped our Accounts within their custom class used for account interactions, selecting synchronous/asynchronous ways. Every operation that composes from other operations should be exposed with variant that accepts results of those other operations.
We might one day to decide to implement Requests differently (like web3j for instance) and we don't want users to depend on `compose` and `map`.

**Comment by cptartur** [comment]
> HttpRequest and HttpResponseDeserializer. There is a problem with HttpResponseDeserializer - it is translated as kotlin's function to java. It has to be changed to either be Function from java or use https://kotlinlang.org/docs/fun-interfaces.html#sam-conversions.

I'd prefer we used `java.util.Function` there. SAM conversions can still be used with it, so it won't complicate our implementations (basically just use `Function { ... }` instead of `{ ... }` when defining lambdas.
