### ISSUE TITLE
`GatewayRequestFailedException` when trying to read storage

### ISSUE THREAD

**Issue by kamilargent** [software-mansion/starknet-jvm#170]
When trying to read storage via `GatewayProvider` I get the following exception.

**Call**: `provider.getStorageAt(accountAddress, Felt(0))`
**Response**: `com.swmansion.starknet.provider.exceptions.GatewayRequestFailedException: invalid literal for int() with base 10: '0x0'`

Looking at `starknet.js` the `key` should be a plain number instead of a hex.

**Comment by Solpatium** [comment]
Thank you for reporting this issue. Fix will be a part of the next release.
We do have tests for that, but devnet accepts both formats https://github.com/Shard-Labs/starknet-devnet/blob/master/starknet_devnet/blueprints/feeder_gateway.py#L189.
