### ISSUE TITLE
starknet-jvm doesn't work on Amazon Linux 2 ARM

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/starknet-jvm#171]
Versions of GLIBCXX supported by Amazon Linux 2:
![image](https://user-images.githubusercontent.com/10278469/199220191-5ec75a7e-0783-4307-bfe2-d137233bef50.png)

Our native component uses symbol
```
0000000000000000      DF *UND*	0000000000000000 (GLIBCXX_3.4.26) _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
```
which requires version 3.4.26, two minor versions above supported by AL2. We have to use older libstdc++ version during build to support Amazon Linux 2. Using GCC 7 should fix the issue.

**Comment by Solpatium** [comment]
I've fixed it for amd64 architecture (https://github.com/software-mansion/starknet-jvm/pull/172), we should also fix it for arm probably.

**Comment by cptartur** [comment]
Should we close this issue and create a more specific one for ARM? This is kind of misleading to have `starknet-jvm doesn't work on Amazon Linux 2` in issues which is not 100% the case now.
