### ISSUE TITLE
transfer failed

### ISSUE THREAD

**Issue by alanpuo** [software-mansion/starknet-jvm#244]
i'm try transfer eth using the code but get error how to fix it, there is the hash: 0x36011aba71feee7eada955ac2582b80b928edf22ea5f4a494ce59fde2623e18
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/13032914/226845809-eb1dd12b-5fac-40b9-98b4-2da5d6d526af.png">

**Comment by THenry14** [comment]
Hello, I am missing some necessary informations to help you with your request; please make sure, that when you open an issue you are using one of the templates https://github.com/software-mansion/starknet-jvm/issues/new/choose.

That being said, I assume you have already declared and deployed a contract, and want to invoke one of its functions to send some eth. please refer to our java demo example on how you might achieve this https://github.com/software-mansion/starknet-jvm/blob/main/javademo/src/main/java/com/example/javademo/Main.java#L59.

I will close this issue now, and if you hav problems please open a new one using one of the templates. Thank you.
