### ISSUE TITLE
Is that a bug?

### ISSUE THREAD

**Issue by Alpha2J** [software-mansion/starknet-jvm#258]
### What happened

can not run with a simple example

### Stack trace

![image](https://github.com/software-mansion/starknet-jvm/assets/17811469/24a04788-b964-4c49-a348-94fda4fb7f6c)

### Steps to reproduce

1. pom.xml
   ```xml
        <dependency>
            <groupId>com.swmansion.starknet</groupId>
            <artifactId>starknet</artifactId>
            <version>0.6.0</version>
        </dependency>
   ```
2. StarknetMain.java
   ```java
   package test;

   import com.swmansion.starknet.account.Account;
   import com.swmansion.starknet.account.StandardAccount;
   import com.swmansion.starknet.data.types.Call;
   import com.swmansion.starknet.data.types.Felt;
   import com.swmansion.starknet.data.types.InvokeFunctionResponse;
   import com.swmansion.starknet.data.types.StarknetChainId;
   import com.swmansion.starknet.data.types.transactions.TransactionReceipt;
   import com.swmansion.starknet.provider.Provider;
   import com.swmansion.starknet.provider.Request;
   import com.swmansion.starknet.provider.rpc.JsonRpcProvider;
   
   import java.util.List;
   import java.util.concurrent.ThreadLocalRandom;
   
   public class StarknetMain {
   public static void main(String[] args) {
        Felt address = Felt.fromHex("0x0468b7AdAE55BE128D1e10D13075A0FFF7e1941014F1C0aC780a35D51658965E");
        Felt privateKey = new Felt(ThreadLocalRandom.current().nextLong(1, Long.MAX_VALUE));
        // tag: replace with rpc url
        Provider provider = new JsonRpcProvider("", StarknetChainId.TESTNET);
        Account account = new StandardAccount(address, privateKey, provider);

        Call call = new Call(Felt.fromHex("0x06f437b6624d8bb9455eedfb26fa99b8267846a05ed2d7f6a03710106f94fcac"), "mint", List.of(Felt.fromHex("0x0468b7AdAE55BE128D1e10D13075A0FFF7e1941014F1C0aC780a35D51658965E"), new Felt(1000)));
        Request<InvokeFunctionResponse> executeRequest = account.execute(call);
        InvokeFunctionResponse executeResponse = executeRequest.send();

        // Make sure that the transaction succeeded
        Request<? extends TransactionReceipt> receiptRequest = provider.getTransactionReceipt(executeResponse.getTransactionHash());
        TransactionReceipt receipt = receiptRequest.send();
        System.out.println(receipt);
    }

   }
   ```
3. Run the main method
4. Got error as the stack trace shown above
5. Decompile Felt.kt, and I did find that it is annotated with `@Serializable`. Since I'm not familiar with Kotlin, I'm unsure whether it is a bug. If it's not, how can it be resolved?
![image](https://github.com/software-mansion/starknet-jvm/assets/17811469/eb0747c4-149f-46cc-aaaa-80198e217aa0)
![image](https://github.com/software-mansion/starknet-jvm/assets/17811469/fcc74f97-69f4-4516-bb4b-c0c5666e2074)

### SDK Version

jdk: corretto-17

### Language

Java

### Language

n/a

### Language version

17

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by Alpha2J** [comment]
And also, I found that `InvokeTransactionPayload` in `TransactionPayload.kt` is lacking some fields according to the JSON RPC defined in [starknet_write_api](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json). Is this library still in experimentation and not stable, even with releases such as v0.6.0?

**Comment by Alpha2J** [comment]
It's only support invoke trasaction v1 and yet invoke transaction v0 is not supported? unsure if is I'm using the wrong starknet-jvm version which is v0.6.0

from `TransactionPayload.kt`
![image](https://github.com/software-mansion/starknet-jvm/assets/17811469/ab042828-0f63-4f11-876e-47e23c4bde49)

from `starknet-spec/api`
![image](https://github.com/software-mansion/starknet-jvm/assets/17811469/8bd72da4-d7a3-405b-abd2-cc31c8af88ba)

**Comment by bartekryba** [comment]
Hey, I'll take a look at it

**Comment by bartekryba** [comment]
Regarding the version of InvokeTransactionPayload, version 0 is deprecated and that's why we only support version 1.
https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#invoke_transaction

**Comment by bartekryba** [comment]
If that's not the case, what Felt format your rpc node uses? `0x` or `0x0` prefixed?
