### ISSUE TITLE
cant use jsonrpc

### ISSUE THREAD

**Issue by popeye2022** [software-mansion/starknet-jvm#265]
### What happened

when i request block and tx , java hass error

`        GetBlockWithTransactionsResponse response = provider.getBlockWithTxs(BlockTag.LATEST).send();
`

### Stack trace

kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for class discriminator 'INVOKE'
JSON input: .....615deade32c6579ebefe4636c5","type":"INVOKE","version":"0x1"}

### Steps to reproduce

        GetBlockWithTransactionsResponse response = provider.getBlockWithTxs(BlockTag.LATEST).send();

### SDK Version

11

### Language

Java

### Language

n/a

### Language version

11

### What operating system are you using?

Windows, Mac

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by THenry14** [comment]
Hi, thanks for opening an issue.

Can you clarify what sdk version are you using? there is no version 11 (latest version is 0.6.1). 

Apart from that, can you provide us with more information? Sadly these steps to reproduce you've provided are not sufficient enough, and this stack trace does not tell us much. Please, show us more of your code and stack trace so it is easier for us to spot/debug the problem.

If you are using an RPC provider, please share its version as well. Thanks.

**Comment by popeye2022** [comment]
i use version 0.6.1
jdk11
this is my code 
`      String url = "https://starknet-goerli.infura.io/v3/fe287803f01d4f309a97cb6e07109039";
        OkHttpClient.Builder builder = new OkHttpClient().newBuilder();
        HttpService httpService =new OkHttpService(builder.build());
        JsonRpcProvider jsonRpcProvider = new JsonRpcProvider(url, StarknetChainId.TESTNET, httpService);
        Integer send = jsonRpcProvider.getBlockNumber().send();
        System.err.println(send);

        GetBlockWithTransactionsResponse send1 = jsonRpcProvider.getBlockWithTxs(BlockTag.LATEST).send();
        System.err.println(send1);`

**Comment by bartekryba** [comment]
I think I found the problem, we'll merge the PR soon (#269)
