### ISSUE TITLE
Improve devnet logging

### ISSUE THREAD

**Issue by DelevoXDG** [software-mansion/starknet-jvm#268]
### Feature Request

- Add --verbose (starknet-devnet >= 0.5.4) to devnetProcess
- Redirect output of devnetProcess to a log file

**Comment by THenry14** [comment]
Cool idea, but I'm afraid --verbose will be a bit too verbose for day-to-day development/usage. It would be interesting though to have this option easily available if someone wants to enable it.

About output redirection - this would be only if --verbose is in place?

**Comment by DelevoXDG** [comment]
This can be picked up once devnet-rs supports --verbose flag.
