### ISSUE TITLE
Add basic flow examples to docs and README 

### ISSUE THREAD

**Issue by THenry14** [software-mansion/starknet-jvm#278]
### Feature Request

- Add invoke/call example
- Add transfer token example
- Add declare cairo 1 contract example

**Comment by legendhlx** [comment]
I want a demo to transfer ETH and other token , thx .

**Comment by amanusk** [comment]
Examples for importing a contract and interacting with it would be very welcome :)

**Comment by DelevoXDG** [comment]
> Examples for importing a contract and interacting with it would be very welcome :)

Hi, I assume you are referring to importing contract using ABI ([like in starknet.py](https://starknetpy.readthedocs.io/en/latest/guide/using_existing_contracts.html)). Unfortunately, at present, starknet-jvm does not support this feature.

However, it does offer capabilities for raw contract invocations and calls using the Provider.callContract and Account.execute methods respectively. We already have invoke examples, we will try to expand the docs to also cover making the calls.
