### ISSUE TITLE
how to get class hash

### ISSUE THREAD

**Issue by popeye2022** [software-mansion/starknet-jvm#283]
### What happened

i declareContract need signature
signature need get txhash 
txhash   need "TransactionHashCalculator.calculateDeclareV1TxHash()". need classhash 
`        Path contractPath = Paths.get(Resources.getResource("Account.json").getPath());
        String contract = "";
        String address = "";
        try {
            contract = String.join("", Files.readAllLines(contractPath));
            // Deploy a contract
            Cairo0ContractDefinition contractDefinition = new Cairo0ContractDefinition(contract);
            Felt addressNonce = new Felt(getAddressNonce(MAIN_ADDRESS).longValue());
            Felt senderAddress = Felt.fromHex(MAIN_ADDRESS);
            DeclareTransactionV1Payload payload = new DeclareTransactionV1Payload(contractDefinition,Felt.ONE, addressNonce,null,senderAddress,Felt.ONE);
            DeclareResponse rpcResponse = provider.declareContract(payload).send();

            TransactionHashCalculator.calculateDeclareV1TxHash()
            Felt newContractAddress = rpcResponse.getClassHash();
            address = newContractAddress.hexString();
        } catch (IOException e) {
            logger.error("deployContract Exception {} ",e);
            throw new ServerException(e.getMessage());
        }`

why not Cairo0ContractDefinition classhash
<img width="1350" alt="image" src="https://github.com/software-mansion/starknet-jvm/assets/112548587/713abf74-b077-4a94-96e0-58a6d64ef389">

### Stack trace

no trace

### Steps to reproduce

1.  i declareContract need signature
2. signature need get txhash 
3. txhash   need "TransactionHashCalculator.calculateDeclareV1TxHash()". need classhash 

### SDK Version

0.6.2

### Language

Java

### Language

n/a

### Language version

java11

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by DelevoXDG** [comment]
Hi @popeye2022 
Sadly, we do not currently have plans to support class hash calculation for contracts written in Cairo 0. The reason behind this is the fact that Cairo 0 will soon be deprecated. 

We strongly advice you to write contracts in Cairo 1. However, if migration is not possible, you will need to compute the class hash for Cairo 0 contracts yourself. One way you could do it is by using [starknet.py](https://github.com/software-mansion/starknet.py). Here's some example code:
```
from starknet_py.contract import Contract
import os


def full_path(relative_path):
    cur_dir = os.path.dirname(os.path.realpath(__file__))
    return os.path.join(cur_dir, relative_path)


def main():
    contract_path = full_path("Account.json")
    with open(contract_path, "r") as f:
        compiled_cairo0_contract_json = f.read()

    class_hash = Contract.compute_contract_hash(compiled_cairo0_contract_json)

    print(hex(class_hash))


if __name__ == "__main__":
    main()
```

Sorry for inconviniece and let me know if you have any other questions.

**Comment by popeye2022** [comment]
https://github.com/OpenZeppelin/cairo-contracts/blob/cairo-2/src/openzeppelin/account/account.cairo
i use openzeppelin source code and compile 
if i use DeclareTransactionV1 will has error 

`com.swmansion.starknet.data.types.Cairo1ContractDefinition$InvalidContractException: Attempted to parse an invalid contract. Missing key: sierra_program
`

**Comment by popeye2022** [comment]
(env) root@d5ef6e9dd96d:/cairo-contracts/artifacts# python ./starknet.py 
Traceback (most recent call last):
  File "/cairo-contracts/artifacts/./starknet.py", line 1, in <module>
    from starknet_py.contract import Contract
ModuleNotFoundError: No module named 'starknet_py'
(env) root@d5ef6e9dd96d:/cairo-contracts/artifacts# python3.9 ./starknet.py 
Traceback (most recent call last):
  File "/cairo-contracts/artifacts/./starknet.py", line 1, in <module>
    from starknet_py.contract import Contract
ModuleNotFoundError: No module named 'starknet_py'
(env) root@d5ef6e9dd96d:/cairo-contracts/artifacts#

**Comment by DelevoXDG** [comment]
Hopefully the exact steps to deploy an account are now clear as the instruction was added to docs: https://github.com/software-mansion/starknet-jvm/pull/287

As for class hash, there are no plans to support class hash calculation for contracts written in Cairo 0. As for deployAccount, you can look up class hashes for existing account contracts on Starknet address book for the needed network:
https://testnet.starkscan.co/address-book
https://testnet-2.starkscan.co/address-book
https://starkscan.co/address-book
