### ISSUE TITLE
When i deploy Contract Account how to fill 'salt' param?

### ISSUE THREAD

**Issue by SephirothLT** [software-mansion/starknet-jvm#337]
### Feature Request

 val classHash = Felt.fromHex(PROXY_BRAAVOS)
        val salt = Felt(0x00000000)
        val calldata = listOf(publicKey)
        val address = ContractAddressCalculator.calculateAddressFromHash(
            classHash = classHash,
            calldata = calldata,
            salt = salt,
        )

**Comment by DelevoXDG** [comment]
Hello 👋🏻 
Generally, you can pass **any** `Felt` value as a salt, although it is advised to generate a unique one. 
You can read more about salt at: https://crypto.stackexchange.com/questions/1776/what-is-a-cryptographic-salt
Let me know if you have any other questions!

**Comment by SephirothLT** [comment]
tks
