### ISSUE TITLE
Java cannot import the 0.8.0 version of the library.

### ISSUE THREAD

**Issue by MuffinPeinVvv** [software-mansion/starknet-jvm#353]
### What happened

ide: idea
maven dependency: 
<dependency>
            <groupId>com.swmansion.starknet</groupId>
            <artifactId>starknet</artifactId>
            <version>0.8.0</version>
</dependency>

when i use this version in my project, i find i cannot import any classes like this:
![img_v3_025e_3f88e67f-fbaf-4416-ab59-811d3ebc624h](https://github.com/software-mansion/starknet-jvm/assets/125015206/93c8837f-0956-4d8f-9c72-14643b5c598d)

### Stack trace

-

### Steps to reproduce

-

### SDK Version

0.8.0

### Language

Java

### Language

n/a

### Language version

8

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by DelevoXDG** [comment]
Hello, can you please tell me what build tool are you using and how exactly are you adding the dependeny?
Have you tried refreshing the project in the plugin dedicated to said build tool?

**Comment by DelevoXDG** [comment]
#354 seems like a reason why you might be unable to load 0.8.0. Although you should still try to refresh the project, since despite #354 imports still should work, even though you won't be able to run it in java. Will try to release 0.8.1 addressing #354 ASAP.

**Comment by MuffinPeinVvv** [comment]
> #354 seems like a reason why you might be unable to import 0.8.0. Still, you should still try to refresh the project, since despite #354 imports still should work, even though you won't be able to run it in java. Will try to release 0.8.1 addressing #354 ASAP.

OK,thanks for  your reply. And I'm an NFT developer looking to use your 0.8.0 version of the MerkleTree type. Maybe I'll need to wait a bit longer.

**Comment by MuffinPeinVvv** [comment]
> Hello, can you please tell me what build tool are you using and how exactly are you adding the dependency? Have you tried refreshing the project in the plugin dedicated to said build tool?

i use maven to build my project. and when i import the maven dependency in my project, my dependency tree like this:
![img_v3_025e_4cfc390f-76e1-432c-94dc-ec305d541bfh](https://github.com/software-mansion/starknet-jvm/assets/125015206/05499f4d-0d2a-475b-b33b-b3971cf677cf)
and then i open the source code of the lib, the tips on my IDEA like:
![1VdLbovjhZ](https://github.com/software-mansion/starknet-jvm/assets/125015206/e1cc49b3-00e2-4e3c-8b1d-a5d1a080cf3b)
I hope this is helpful for you in solving the issue.

**Comment by DelevoXDG** [comment]
@MuffinPeinVvv 
The issue should be resolved in 0.8.1. 
Let me know if everything works as expected now.

**Comment by MuffinPeinVvv** [comment]
> @MuffinPeinVvv The issue should be resolved in 0.8.1. Let me know if everything works as expected now.

i close kotlin plugin in my IDEA and use 0.8.1 in my project. it works.
