### ISSUE TITLE
How can I obtain a proof for a specific Merkle tree node.

### ISSUE THREAD

**Issue by MuffinPeinVvv** [software-mansion/starknet-jvm#360]
### Feature Request

From what I've seen, there isn't a method in your implementation of the Merkle tree for obtaining this specific proof.
Have you considered supporting this feature?

**Comment by DelevoXDG** [comment]
Hi, thanks for your suggestion.

This seems like a good feature to add, although the SDK is currently in maintenance mode. We will discuss this internally and I will let you know

**Comment by DelevoXDG** [comment]
Hello @MuffinPeinVvv, I have a few extra questions:
1.  Is there any particular application for this you have in mind?
2. Have you tried getting the proof some other way, or implementing a method for obtaining it yourself (e.g. basing on starknet.js [implementation](https://github.com/starknet-io/starknet.js/blob/7e0cffa3afd90265d2571b8ec0a1be39411a10ce/src/utils/merkle.ts#L55))? We are currently unsure that this should be a part of SDK.

Considering the feature's limited demand and our focus on higher-priority updates, the potential wait time might make it irrelevant by the time it's added.

**Comment by MuffinPeinVvv** [comment]
> Hello @MuffinPeinVvv, I have a few extra questions:
> 
> 1. Is there any particular application for this you have in mind?
> 2. Have you tried getting the proof some other way, or implementing a method for obtaining it yourself (e.g. basing on starknet.js [implementation](https://github.com/starknet-io/starknet.js/blob/7e0cffa3afd90265d2571b8ec0a1be39411a10ce/src/utils/merkle.ts#L55))? We are currently unsure that this should be a part of SDK.
> 
> Considering the feature's limited demand and our focus on higher-priority updates, the potential wait time might make it irrelevant by the time it's added.

I found a 'branches' field in the MerkleTree class. I can use this field to write a method that constructs the entire tree structure and then retrieves the proof for each node.  like this :
![image](https://github.com/software-mansion/starknet-jvm/assets/125015206/282b3670-18fa-4527-bedf-88e0737954d4)
If you could provide a method that users can use, it would be even better.

**Comment by DelevoXDG** [comment]
Hello!  
While this is a good idea, we're currently focused on keeping our core functionalities up to date, so I'm closing this for now. 

Thank you for your suggestion!
