### ISSUE TITLE
How to use your SDK to decode an event.

### ISSUE THREAD

**Issue by MuffinPeinVvv** [software-mansion/starknet-jvm#369]
### Feature Request

There is an on-chain event in StarkNet, and its row format is as follows.
![image](https://github.com/software-mansion/starknet-jvm/assets/125015206/79f2124c-c931-4f54-9143-0098b71d7ddf)
The ABI for the event is as follows.
![image](https://github.com/software-mansion/starknet-jvm/assets/125015206/1e197f22-097e-440e-9dc7-de862c2ffceb)
How to use your SDK to decode this event like this:
![image](https://github.com/software-mansion/starknet-jvm/assets/125015206/0a2ef01a-24ae-49a4-b9eb-934d28862a8b)

**Comment by DelevoXDG** [comment]
Hi @MuffinPeinVvv, 

Can you please send the link to the contract on starkscan so I can take a better look at it?

**Comment by MuffinPeinVvv** [comment]
> Hi @MuffinPeinVvv,
> 
> Can you please send the link to the contract on starkscan so I can take a better look at it?
such as OrderExecuted event from unframed marketplace :
https://starkscan.co/tx/0x222b6a88de80b0df3da5b7032e9fdd1aebf98671fe05ad53b7079c540b16dd#events

**Comment by DelevoXDG** [comment]
If you know the transaction hash, you can get all events emitted by the given transaction. Since you know this event is from Unframed marketplace, you can further filter by `0x051734077ba7baf5765896c56ce10b389d80cdcee8622e23c0556fb49e82df1b`. 

We don't however automatically parsing the data though, so you will need to decode it manually.

Example code:
```kotlin
import com.swmansion.starknet.data.types.*
import com.swmansion.starknet.provider.rpc.JsonRpcProvider

val provider = JsonRpcProvider("https://example.com/rpc/v0_6", StarknetChainId.MAINNET)

val txHash = Felt.fromHex("0x00222b6a88de80b0df3da5b7032e9fdd1aebf98671fe05ad53b7079c540b16dd")
val tx = provider.getTransactionReceipt(txHash).send()

tx.events.findLast {
    it.address == Felt.fromHex("0x51734077ba7baf5765896c56ce10b389d80cdcee8622e23c0556fb49e82df1b")
}?.let { event ->
    println(event.data.size)
    println(event.data)
    val amount = Uint256(event.data[0], event.data[1])
    val price = Uint256(event.data[2], event.data[3])
    val totalFee = Uint256(event.data[4], event.data[5])
    val address = event.data[6]
    println("""
        amount: $amount
        price: $price
        totalFee: $totalFee
        address: $address
    """.trimIndent())
}
```

**Comment by DelevoXDG** [comment]
I assume the issue is now resolved 👍🏻
