### ISSUE TITLE
Add missing transaction properties.

### ISSUE THREAD

**Issue by bartekryba** [software-mansion/starknet-jvm#42]
Make sure that all transaction properties that are present in starknet-spec are also present in our transaction data classes.

My proposal for working with both gateway and rpc:
* fields present in gateway, but not in rpc => Ignore them
* fields present in rpc but not in gateway => Make them non-optional (if they are so in the spec) and use some dummy value for them (like 0 for felts)

**Comment by cptartur** [comment]
Dummy values is probably the most convenient solution for the RPC users but it can be a little bit confusing. I'd definitely rule out creating subclasses for gateway responses, so unfortunately it's either this or optional values.

What do you think @Solpatium

**Comment by Solpatium** [comment]
> I'd definitely rule out creating subclasses for gateway responses

Why? This creates the best (type safe) UX for users.

**Comment by cptartur** [comment]
I think maintaining different data classes for RPC and different for gateway will just add unnecessary complication plus it's not obvious how they would be related which would complicate the provider interface. If gateway is to be gone relatively soon I believe it's better if we only had data classes modeled after rpc where possible and somehow map gateway responses to them.

**Comment by Solpatium** [comment]
> it's not obvious how they would be related

They would extend the same interface. 

I think we can start with things with common properties first.

**Comment by cptartur** [comment]
Closed in #50
