### ISSUE TITLE
Remove support for Goerli chain ID

### ISSUE THREAD

**Issue by DelevoXDG** [software-mansion/starknet-jvm#425]
### Feature Request

Goerli networks are expected to shut down by Aprill 11, after that we should remove hardcoded Goerli chian ID. 

If possible, we should also remove all mentions of Goerli in demos, examples, tests etc.

**Comment by DelevoXDG** [comment]
Blocked for now, let's unblock this in April

**Comment by THenry14** [comment]
https://github.com/software-mansion/starknet-jvm/issues/384
