### ISSUE TITLE
Build & host documentation online

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/starknet-jvm#60]
Just like protostar (https://docs.swmansion.com/protostar/).

**Comment by Solpatium** [comment]
@cptartur please add description

**Comment by cptartur** [comment]
Currently our documentation is set up to be built using [Dokka](https://github.com/Kotlin/dokka). There are two gradle tasks configured: `dokkaHtml` and `dokkaHtmlJava`, which converts kotlin code to java before building documentation. 

Ideally we would both kotlin and java verison of this docs, and also include them in jar hosted on maven.
It seems like it is possible with dokka, [see this](https://github.com/Kotlin/dokka/blob/master/README.md#using-the-maven-plugin).
