### ISSUE TITLE
Add starknet-jvm to lists of Starknet tools

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/starknet-jvm#81]
We need to add PRs to:
- https://github.com/gakonst/awesome-starknet
- https://github.com/beautyisourbusiness/cairo-goldmine
- https://www.starknet-ecosystem.com/

There might be more lists like that.

**Comment by Solpatium** [comment]
Added:
- https://github.com/gakonst/awesome-starknet/pull/40
- https://github.com/beautyisourbusiness/cairo-goldmine/pull/13
- https://github.com/419Labs/starknet-ecosystem.com/pull/113

Will close this ticket once those PRs are merged.

**Comment by cptartur** [comment]
All referenced PRs were merged.
