### ISSUE TITLE
Delete version parameter, from methods related to invoking contracts.

### ISSUE THREAD

**Issue by bartekryba** [software-mansion/starknet-jvm#85]
Remove `version` parameter from methods related to invoking contracts, and make it fixed and related to transaction model.

**Comment by cptartur** [comment]
How exactly should we be approaching this? Currently invokeTransaction (and any other method) payload is modelled on RPC specs and are used directly in the RPC provider. Removing `version` parameter from payload entirely would break that assumption.

**Comment by bartekryba** [comment]
We don't want to delete it entirely, just hide it from the user, so they don't have to provide it explicitly. It will still be in payload, as well as transaction, but as a fixed value

**Comment by cptartur** [comment]
Makes sense. I'd wait with resolving this issue until at least #82 is dealt with.
