### ISSUE TITLE
Improve [package specific] docs

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet-jvm#98]
It is possible to document specific packages by adding `# Package full.path.to.package` sections to `starknet-jvm.md`. We can consider including example usages and more details about specific library modules there.

**Comment by cptartur** [comment]
It seems like these are only included in the kotlin docs, javadoc seems to ignore these entirely. 
[Compare this](https://docs.swmansion.com/starknet-jvm/kotlin/starknet-jvm/com.swmansion.starknet.account/index.html) with [this](https://docs.swmansion.com/starknet-jvm/com/swmansion/starknet/account/package-summary.html).

**Comment by cptartur** [comment]
Related to #138

**Comment by THenry14** [comment]
Improve everything in docs :+1:
